name: "TotalGroupPlaceholder"
version: "1.4-FORKED"
main: "com.user.totalgroupplaceholder.TotalGroupPlaceholderPlugin"
api-version: "1.13"
api: "PlaceholderAPI"
authors:
  - XtoManuel
  - biiee3l
depend:
  - "PlaceholderAPI"
  - "LuckPerms"

commands:
  totalgroup:
    description: "Shows the number of members in a LuckPerms group"
    usage: "/totalgroup <group|all>"
    permission: "totalgroup.use"
    default: "op"
